### ISSUE TITLE
Spec out MVP

### ISSUE THREAD

**Issue by davclark** [BIDS/garmr#4]
- [x] Determine current data schema for front desk (i.e., from google sheets). We definitely collect [this](http://bids.berkeley.edu/bids-membership-application).
- [x] Determine "personas" - i.e., kinds of people (members, fellows, guests for events, guests of members)
- [x] What kinds of signage / documentation will we have?
- [x] Procedure for front desk staff
- [ ] Why are we collecting data? (I.e., reports to Moore–Sloan, security)

While we're at it - get the configuration for how the system works in the Invention lab. (@davclark has some of this info.)

**Comment by echiou** [comment]
#### Current Schema
- The information we currently store in the check-in sheet includes:
  - Name
  - BIDS Affiliation & Position
  - E-mail
  - Department
  - Check-in dates
    - An "X" for dates that the members came into BIDS, as recorded by people at the front desk. (Check-in but no check-out, prone to human error.)
- Additionally, we also get "Title", as well as an Application and a Faculty Sponsorship Letter from the membership application.

#### Personas
- As currently listed on the check-in sheets, our various BIDS affiliations include:
  - Senior Fellows
  - Fellows
  - Members
  - Student Members
  - Guests & Visitors
  - Guests attending events in the space
  - Members of the Data Science Collaborative

**Comment by echiou** [comment]
#### Signage & Documentation (In Progress)
- We want to be as transparent as possible, yet make it as painless as possible for people to sign in and out.
  - Sign-in "station", where people must put their name in (or tap their badge), which puts in all the information we need (will at least be more accurate and robust than the current implementation.
  - Allows easy change to check in guests, or to put guests into events (we should think about changing the schema here as well, e.g. do we really need event guess affiliation/department?)
- Badge vs. Pin
  - Badge - can just get a card reader, easy to sign in, everyone already has one (Cal ID)
  - Pin - harder to implement, long-range RFID? This will allow for easier sign-OUT, however. This can be opt-in, in addition to the sign-in station.
- Essentially, need to somehow convince people coming in that they have to sign in (or switch to one of the more automated ways) through the signage.

#### Procedure (In Progress)
- Hopefully can connect this to Google Sheets (or whatever else that can update in real-time), so the front desk staff can monitor and enforce sign-in.
- Essentially the same as current procedure, but the front desk does not have to manually input data on people coming in, simply monitor it.

**Comment by davclark** [comment]
I've moved the above to [the wiki](https://github.com/BIDS/garmr/wiki).
